### ISSUE TITLE
Workitems not created by me if I filed the bug and someone else approved it

### ISSUE THREAD

**Issue by ostreifel** [mohitbagra/vsts-extensions-bugbash-pro#26]
I have a query to track the status of all the bugs I created and bugs from bug bashes are going to slip through it. Current mentions doesn't help because that macro doesn't go back further than 30 days.

**Comment by mohitbagra** [comment]
This is not doable via rest APIs as we can't impersonate another user via WIT rest call (unless I have their PAT). If we start using a different field, similar to "Created by" which is not set by a server rule, then may be we can do it.
Or if you agree to give me your PAT, then I can make the rest call on your behalf :) @ostreifel

**Comment by ostreifel** [comment]
I don't understand why the extension does not create a work item when I file an issue in the bug bash. This delayed logic creates all kinds of issues with attribution. If I create an issue and 35 people then modify the description and then some one else accepts the issue then the entire issue is created by the accepter and I am the only person mentioned as who it was created on behalf of and those 35 changes by 35 different people are all flattened. This is data loss that makes querying on that lost information impossible.

I think the solution is to stop delaying these create and edit events on workitems.

**Comment by ostreifel** [comment]
This is exacerbated if I file a lot of bugs and want to monitor their status after the bug bash - the most common use case of the extension.

**Comment by mohitbagra** [comment]
The extension has a "Auto accept" setting on each bug bash instance. If we turn it on while creating a bug bash instance, then creating an item will create workitem directly. My v1 of the extension had the same functionality that you suggested, but I got feedback from a lot of folks to not create the workitem right away. Thats why I added this new feature in v2. If Auto-accept is off, it doesnt create a workitem right away. If its on, it does.

So far, no one has objected to it, so I think everyone likes having Auto-Accept off, because it lets people triage the bugs effectively.
